openapi: 3.0.0
info:
  title: Challenge Code API 
  description: Challenge Code API fro reading and scraping articles from bbc new website
  version: 0.1.9
servers:
  - url: '/v1'
    description: Optional server description, e.g. Main (production) server

paths:
  /scrape_data:
    get:
      operationId: controllers.main_controller.scrape_data
      summary: scrape BBC website and save data in mongodb collection
      description: scrape
      responses:
        '200':    # status code
          description: 'scraping is done succesufly ' 

        '400':
          description: 'Bad request'
        '401':
          description: 'Authorization information is missing or invalid.'
        '5XX':
          description: 'Unexpected error.'

  /read_data:
    get:
      operationId: controllers.main_controller.read_data
      summary: read data from mongodb collection
      description: read data
      responses:
        '200':    # status code
          description: 'reading is done succesufly is done succesufly ' 
          content:
            application/json:
              schema: 
                type: object
                properties:
                  "news_articles":
                    type : array
                    items:
                      type: object
                      additionalProperties:
                        type: string
        '400':
          description: 'Bad request'
        '401':
          description: 'Authorization information is missing or invalid.'
        '5XX':
          description: 'Unexpected error.'

          
                  
  /fetch_data:
    post:
      operationId: controllers.main_controller.fetch_data
      summary: fetch data from mongodb collection using keyword
      description: fetching data
      requestBody:
              required : True
              content:
                application/json :
                  schema:
                    properties:
                      "keyword":
                        type: string
                        minLength: 3
                        maxLength: 20
      responses:
        '200':    # status code
          description: 'featching is done succesufly is done succesufly ' 
          content:
            application/json:
              schema: 
                type: object
                properties:
                  "news_articles":
                    type : array
                    items:
                      type: object
                      additionalProperties:
                        type: string
        '400':
          description: 'Bad request'
        '401':
          description: 'Authorization information is missing or invalid.'
        '5XX':
          description: 'Unexpected error.'
                  
